name: Alpaca RSI+MA Bot (Real-Time Crypto Scalper)

on:
  workflow_dispatch:  # manual trigger from GitHub UI

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install alpha_vantage

      - name: Check installed packages
        run: pip list

      - name: Run real-time crypto scalper bot
        env:
          APCA_API_KEY_ID: ${{ secrets.APCA_API_KEY_ID }}
          APCA_API_SECRET_KEY: ${{ secrets.APCA_API_SECRET_KEY }}
          RSI_PERIOD: 14
          BUY_THRESHOLD: 30
          SELL_THRESHOLD: 70
          COOLDOWN_SECONDS: 60
        run: python real_time_crypto_scalper.py
