name: Alpaca RSI+MA Bot (Real-Time Crypto Scalper)

on:
  workflow_dispatch:  # manual trigger from GitHub UI

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
          run: |
            pip install --upgrade pip
            pip install --upgrade alpaca-trade-api alpha_vantage
            pip install -r requirements.txt


      - name: Run real-time crypto scalper bot
        env:
          APCA_API_KEY_ID: ${{ secrets.APCA_API_KEY_ID }}
          APCA_API_SECRET_KEY: ${{ secrets.APCA_API_SECRET_KEY }}
          RSI_PERIOD: 14
          BUY_THRESHOLD: 30
          SELL_THRESHOLD: 70
          COOLDOWN_SECONDS: 60  # optional cooldown time between trades per symbol
        run: python real_time_crypto_scalper.py
